# @TAG(NICTA_BSD)
#

apps-$(CONFIG_APP_TESTDATAPORTBIFURCATE) += testdataportbifurcate
testdataportbifurcate: libsel4 libmuslc libsel4platsupport libsel4muslccamkes libsel4camkes libsel4sync libsel4bench
