# @TAG(DATA61_BSD)
#

apps-$(CONFIG_APP_TESTSEL4NOTIFICATION) += testsel4notification
testsel4notification: libsel4 libmuslc libsel4platsupport libsel4muslccamkes libsel4camkes libsel4sync libsel4bench
