#
# Copyright 2015, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

TARGETS := $(notdir ${SOURCE_DIR}).cdl
ADL := $(notdir ${SOURCE_DIR}).camkes

Driver1_CFILES := driver1.c
Driver1_HFILES := driver.h
Driver2_CFILES := driver2.c
Driver2_HFILES := driver.h

include ${PWD}/tools/camkes/camkes.mk
