# @TAG(DATA61_BSD)
#

TARGETS := $(notdir ${SOURCE_DIR}).cdl
ADL := $(notdir ${SOURCE_DIR}).camkes

Driver1_CFILES := driver1.c
Driver1_HFILES := driver.h
Driver2_CFILES := driver2.c
Driver2_HFILES := driver.h

include ${PWD}/tools/camkes/camkes.mk
