# @TAG(DATA61_GPL)
#

TARGETS := $(notdir ${SOURCE_DIR}).cdl
ADL := binary-semaphore.camkes

Client_CFILES := ${SOURCE_DIR}/src/client.c
Server_CFILES := ${SOURCE_DIR}/src/server.c
Periodic_CFILES := ${SOURCE_DIR}/src/periodic.c

include ${PWD}/tools/camkes/camkes.mk
