#
# Copyright 2016, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

apps-$(CONFIG_APP_AEROPLAGE) += aeroplage
aeroplage: libsel4 libmuslc libsel4muslccamkes libsel4camkes libsel4sync libsel4bench libringbuffer libsel4bga libsel4keyboard
