# @TAG(NICTA_BSD)
#

apps-$(CONFIG_APP_TESTHARDWAREINTERRUPT) += testhardwareinterrupt
testhardwareinterrupt: libsel4 libmuslc libsel4platsupport libsel4muslccamkes libsel4camkes libsel4sync libsel4bench
