/*
 * Copyright 2017, Data61, CSIRO (ABN 41 687 119 230)
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

#pragma once

#define REVERSE_STRING_BUFSIZE 4096
#define REVERSE_STRING_END_IDX (REVERSE_STRING_BUFSIZE - 1)
#define REVERSE_STRING_MAX_LEN (REVERSE_STRING_END_IDX - 1)
