# @TAG(NICTA_BSD)
#

apps-$(CONFIG_APP_TESTREPLYCAPPROTECTION) += testreplycapprotection
testreplycapprotection: libsel4 libmuslc libsel4platsupport libsel4muslccamkes libsel4camkes libsel4sync libsel4bench
