# @TAG(NICTA_BSD)
#

TARGETS := $(notdir ${SOURCE_DIR}).cdl
ADL := $(notdir ${SOURCE_DIR}).camkes

Generator_CFILES := generator.c
Receiver_CFILES := receiver.c
Responder_CFILES := responder.c
Caller_CFILES := caller.c

include ${PWD}/tools/camkes/camkes.mk
