# @TAG(NICTA_BSD)
#

TARGETS := $(notdir ${SOURCE_DIR}).cdl
ADL := $(notdir ${SOURCE_DIR}).camkes

Client_CFILES := client.c
Intermediary_CFILES := intermediary.c
Server_CFILES := server.c

include ${PWD}/tools/camkes/camkes.mk
