# @TAG(NICTA_BSD)
#

TARGETS := $(notdir ${SOURCE_DIR}).cdl
ADL := $(notdir ${SOURCE_DIR}).camkes

Client_CFILES := client.c
Client_HFILES := my_struct.h
Server_CFILES := server.c
Server_HFILES := my_struct.h

include ${PWD}/tools/camkes/camkes.mk
