# @TAG(NICTA_BSD)
#

TARGETS := $(notdir ${SOURCE_DIR}).cdl
ADL := $(notdir ${SOURCE_DIR}).camkes

A_HFILES := heap_check.h 
A_CFILES := A.c
B_CFILES := B.c
C_HFILES := heap_check.h 
C_CFILES := C.c

include ${PWD}/tools/camkes/camkes.mk
