# @TAG(DATA61_BSD)
#

TARGETS := $(notdir ${SOURCE_DIR}).cdl
ADL := $(notdir ${SOURCE_DIR}).camkes

Client_CFILES := client.c
Client_HFILES := ctypes.h
Server_CFILES := server.c
Server_HFILES := ctypes.h

include ${PWD}/tools/camkes/camkes.mk
